#!/usr/bin/env ruby

require 'fileutils'

folders_to_delete = Dir['*/'].select { |path| !path.match?(/^_/) }
folders_to_delete.each { |path| FileUtils.remove_dir(path) }

files_to_delete = Dir['./*.*'].select { |path| !path.match?(/build.rb/) }
files_to_delete.each { |path| File.delete(path) }

`rm -rf _jekyll/_posts`
`cp -R _posts _jekyll/_posts`
`cd _jekyll && bundle install && bundle exec jekyll build`

# def copy_with_path(src, dst)
#   FileUtils.mkdir_p(File.dirname(dst))
#   FileUtils.mv(src, dst)
# end

# Dir['./_jekyll/_site/**/*.*'].each do |path|
#   copy_with_path(path, path.gsub('./_jekyll/_site', '.'))
# end

